//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISRPO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash
    {
        public string Namee { get; set; }
        public decimal Price { get; set; }
        public string Quantity { get; set; }
        public decimal Sum { get; set; }
    }
}
